/*
 * Golden-fixture replay tests.
 *
 * tests/fixtures/{named,random}.json are generated by the Rust harness in
 * fixture-gen/ from the vendored sapling-renderdag crate (see
 * vendor/SAPLING_COMMIT for the exact upstream commit). Each case replays a
 * sequence of reserve/row steps; we assert that the TypeScript port produces
 * byte-identical text output, identical widths, and identical structured
 * GraphRow output.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';

import { Ancestor, GraphRowRenderer } from '../src/index.js';
import type { GraphRow, OutputRendererOptions, Renderer } from '../src/index.js';
import { GraphTextRenderer } from '../src/pipeline/graph_text_renderer.js';
import { AsciiPrefixLineRenderer } from '../src/pipeline/row_shape_to_prefix_lines/ascii.js';
import { AsciiLargePrefixLineRenderer } from '../src/pipeline/row_shape_to_prefix_lines/ascii_large.js';
import {
  BoxDrawingPrefixLineRenderer,
  CURVED_GLYPHS,
  DEC_GLYPHS,
  SQUARE_GLYPHS,
} from '../src/pipeline/row_shape_to_prefix_lines/box_drawing.js';
import type { PrefixLineRenderer } from '../src/pipeline/types.js';

type FixtureParent = ['parent', string] | ['ancestor', string] | ['anonymous'];

interface FixtureTextExpect {
  width: number;
  out: string;
}

interface FixtureStep {
  type: 'reserve' | 'row';
  node: string;
  parents?: FixtureParent[];
  glyph?: string;
  message?: string;
  expect?: {
    widths: { none: number; node: number; full: number };
    graphRow: {
      merge: boolean;
      separatorLine: boolean;
      nodeLine: string[];
      linkLine: number[] | null;
      termLine: boolean[] | null;
      padLines: string[];
    };
    text: Record<string, FixtureTextExpect>;
  };
}

interface FixtureCase {
  name: string;
  options: { minRowHeight: number; stagger: boolean };
  steps: FixtureStep[];
}

const here = dirname(fileURLToPath(import.meta.url));

function loadCases(file: string): FixtureCase[] {
  return JSON.parse(readFileSync(join(here, 'fixtures', file), 'utf8')) as FixtureCase[];
}

function toAncestors(parents: FixtureParent[]): Ancestor<string>[] {
  return parents.map((p) =>
    p[0] === 'parent'
      ? Ancestor.parent(p[1]!)
      : p[0] === 'ancestor'
        ? Ancestor.ancestor(p[1]!)
        : Ancestor.anonymous<string>(),
  );
}

const TEXT_STYLES = ['ascii', 'asciiLarge', 'boxCurved', 'boxSquare', 'boxDec'] as const;
type TextStyle = (typeof TEXT_STYLES)[number];

function buildTextRenderer(
  style: TextStyle,
  options: OutputRendererOptions,
): Renderer<string, string> {
  const builder = new GraphRowRenderer<string>().output().withOptions(options);
  switch (style) {
    case 'ascii':
      return builder.buildAscii();
    case 'asciiLarge':
      return builder.buildAsciiLarge();
    case 'boxCurved':
      return builder.buildBoxDrawing();
    case 'boxSquare':
      return builder.buildBoxDrawing().withSquareGlyphs();
    case 'boxDec':
      return builder.buildBoxDrawing().withDecGraphicsGlyphs();
  }
}

function buildPrefixLineRenderer(style: TextStyle): PrefixLineRenderer<string> {
  switch (style) {
    case 'ascii':
      return new AsciiPrefixLineRenderer();
    case 'asciiLarge':
      return new AsciiLargePrefixLineRenderer();
    case 'boxCurved':
      return new BoxDrawingPrefixLineRenderer(CURVED_GLYPHS);
    case 'boxSquare':
      return new BoxDrawingPrefixLineRenderer(SQUARE_GLYPHS);
    case 'boxDec':
      return new BoxDrawingPrefixLineRenderer(DEC_GLYPHS);
  }
}

function optionsOf(fixture: FixtureCase): OutputRendererOptions {
  return {
    minRowHeight: fixture.options.minRowHeight,
    staggerConsecutiveDisconnectedNodes: fixture.options.stagger,
  };
}

function runCase(fixture: FixtureCase): void {
  const options = optionsOf(fixture);

  // Structured renderer (classic GraphRowRenderer API).
  const graph = new GraphRowRenderer<string>();
  Object.assign(graph.outputOptions(), options);

  // Classic text renderers.
  const texts = new Map<TextStyle, Renderer<string, string>>(
    TEXT_STYLES.map((style) => [style, buildTextRenderer(style, options)]),
  );

  // Pipeline GraphTextRenderer instances: must produce the same text as the
  // classic wrappers row-for-row.
  const pipelineTexts = new Map<TextStyle, GraphTextRenderer<string>>(
    TEXT_STYLES.map((style) => {
      const renderer = new GraphTextRenderer<string>(buildPrefixLineRenderer(style)).configure(
        (o) => Object.assign(o, options),
      );
      return [style, renderer];
    }),
  );

  for (const [stepIndex, step] of fixture.steps.entries()) {
    if (step.type === 'reserve') {
      graph.reserve(step.node);
      for (const t of texts.values()) t.reserve(step.node);
      for (const t of pipelineTexts.values()) t.reserve(step.node);
      continue;
    }

    const expect_ = step.expect!;
    const at = `${fixture.name} step ${stepIndex} node ${step.node}`;

    // Widths on the structured renderer.
    expect(graph.width(null, null), `${at} width(none)`).toBe(expect_.widths.none);
    expect(graph.width(step.node, null), `${at} width(node)`).toBe(expect_.widths.node);
    const parents = toAncestors(step.parents!);
    expect(graph.width(step.node, parents), `${at} width(full)`).toBe(expect_.widths.full);

    // Structured GraphRow output.
    const row: GraphRow<string> = graph.nextRow(step.node, parents, step.glyph!, step.message!);
    expect(row.node, at).toBe(step.node);
    expect(row.glyph, at).toBe(step.glyph);
    expect(row.message, at).toBe(step.message);
    expect(
      {
        merge: row.merge,
        separatorLine: row.separatorLine,
        nodeLine: row.nodeLine,
        linkLine: row.linkLine,
        termLine: row.termLine,
        padLines: row.padLines,
      },
      `${at} graphRow`,
    ).toEqual(expect_.graphRow);

    // Text renderers: width + byte-identical output.
    for (const style of TEXT_STYLES) {
      const t = texts.get(style)!;
      const styleParents = toAncestors(step.parents!);
      expect(t.width(step.node, styleParents), `${at} ${style} width`).toBe(
        expect_.text[style].width,
      );
      const out = t.nextRow(step.node, styleParents, step.glyph!, step.message!);
      expect(out, `${at} ${style} text`).toBe(expect_.text[style].out);

      // Pipeline path must agree with the classic wrapper.
      const p = pipelineTexts.get(style)!;
      const pipelineOut = p.nextText(
        step.node,
        toAncestors(step.parents!),
        step.glyph!,
        step.message!,
      );
      expect(pipelineOut, `${at} ${style} pipeline text`).toBe(expect_.text[style].out);
    }
  }
}

for (const file of ['named.json', 'random.json']) {
  describe(file, () => {
    for (const fixture of loadCases(file)) {
      test(fixture.name, () => runCase(fixture));
    }
  });
}
